"""kaggle: runs a train stage as a private Kaggle script kernel on a free GPU.

Kaggle takes one source file, so the kernel embeds the g1pipe bundle, the reporter and the rendered
argv, the same way scripts/kaggle_job.py does (its PINS, BUNDLE and NOISE are imported from that file,
which stays the single source of truth). Warm starts mount the parent kernel's output through
`kernel_sources`. All calls go through the `kaggle` CLI with the key in its environment only.
"""

from __future__ import annotations

import ast
import asyncio
import csv
import functools
import importlib.util
import json
import os
import re
import shutil
import sys
import tempfile
import time
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field

from skf_api.backends._job import JOB_LOG, REPORTER_RELPATH, copy_tree, ingest_env, render_argv, reporter_args
from skf_api.backends._proc import ProcessRunner, ProcResult, SubprocessRunner
from skf_api.backends.base import (
    BackendError,
    BackendKind,
    ExternalRef,
    HealthReport,
    HealthStatus,
    JobSpec,
    JobState,
    JobStatus,
    LogBatch,
    TargetContext,
)

KAGGLE_URL = "https://www.kaggle.com/code"
WORKING = "/kaggle/working"
OUT_DIR = f"{WORKING}/run"
INPUT_DIR = "/tmp/skf-in"  # noqa: S108 - a path inside the Kaggle container, not on this host
LOG_LIMIT_BYTES = 2 * 1024 * 1024
# Kaggle can take a moment to list a freshly pushed kernel; until then "not found" means "queued".
NOT_FOUND_GRACE_SECONDS = 300
_ENV_PASSTHROUGH = (
    "PATH",
    "HOME",
    "LANG",
    "LC_ALL",
    "TMPDIR",
    "SSL_CERT_FILE",
    "REQUESTS_CA_BUNDLE",
    "HTTPS_PROXY",
    "HTTP_PROXY",
    "NO_PROXY",
    "https_proxy",
    "http_proxy",
    "no_proxy",
)

_STATES = {
    "queued": JobState.PROVISIONING,
    "newscript": JobState.PROVISIONING,
    "running": JobState.RUNNING,
    "complete": JobState.SUCCEEDED,
    "error": JobState.FAILED,
    "cancelrequested": JobState.CANCELLED,
    "cancelacknowledged": JobState.CANCELLED,
}

KERNEL_TEMPLATE = """\
# Generated by SKF Skill Studio for run {run_name}, stage {stage_key} ({stage_id}).
# Edit g1pipe/ in the repository instead; this file is rebuilt for every run.
import os, pathlib, shutil, subprocess, sys
subprocess.run(["nvidia-smi"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *{pins!r}])
SRC = pathlib.Path("/kaggle/working/src")
for rel, text in {files!r}.items():
    (SRC / rel).parent.mkdir(parents=True, exist_ok=True)
    (SRC / rel).write_text(text)
# warm start: outputs of earlier kernels (kernel_sources) are mounted read-only under /kaggle/input
for name, kernel in {inputs!r}.items():
    slug = kernel.split("/")[-1]
    found = sorted(pathlib.Path("/kaggle/input").rglob(pathlib.PurePosixPath(name).name),
                   key=lambda p: slug not in str(p))
    if not found:
        subprocess.run(["find", "/kaggle/input", "-maxdepth", "4"])
        sys.exit(f"input {{name}} from kernel {{kernel}} not found under /kaggle/input")
    target = pathlib.Path({input_dir!r}) / name
    target.parent.mkdir(parents=True, exist_ok=True)
    target.symlink_to(found[0])
    print("input", name, "<-", found[0], flush=True)
env = dict(os.environ, PYTHONPATH=str(SRC), PYTHONUNBUFFERED="1", XLA_PYTHON_CLIENT_MEM_FRACTION="0.9")
env.update({env!r})
reporter = [sys.executable, str(SRC / "skf_reporter.py"), *{reporter!r}]
rc = subprocess.call([*reporter, "--", sys.executable, *{argv!r}], env=env)
shutil.rmtree(SRC, ignore_errors=True)
sys.exit(rc)
"""


class KaggleConfig(BaseModel):
    model_config = ConfigDict(extra="forbid", title="Kaggle")

    username: str = Field(..., min_length=1, pattern=r"^[A-Za-z0-9_-]+$", description="Kaggle account name")
    accelerator: str = Field("NvidiaTeslaT4", description="Kaggle machine shape, e.g. NvidiaTeslaT4")
    kernel_prefix: str = Field(
        "skf",
        pattern=r"^[a-z0-9][a-z0-9-]{0,15}$",
        description="Prefix of the private kernel slugs this target creates",
    )
    enable_internet: bool = Field(True, description="Kernels need internet to install the pinned packages")


class KaggleSecret(BaseModel):
    model_config = ConfigDict(extra="forbid", title="Kaggle credentials")

    key: str = Field(
        ...,
        min_length=1,
        repr=False,
        json_schema_extra={"format": "password", "writeOnly": True},
        description="API key from kaggle.com/settings (the `key` in kaggle.json)",
    )


@dataclass(frozen=True)
class PipelineBundle:
    """What scripts/kaggle_job.py pins and ships; loaded from that file so both paths stay identical."""

    pins: list[str]
    bundle: list[str]
    noise: tuple[str, ...]


@functools.cache
def load_pipeline_bundle(kaggle_job: Path) -> PipelineBundle:
    spec = importlib.util.spec_from_file_location("skf_kaggle_job", kaggle_job)
    if spec is None or spec.loader is None:
        raise BackendError(f"cannot load {kaggle_job}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    # NOISE lives inside kaggle_job's kernel template, not at module level
    match = re.search(r"^NOISE = (\(.*\))$", module.KERNEL, re.MULTILINE)
    if match is None:
        raise BackendError(f"NOISE not found in {kaggle_job}")
    return PipelineBundle(list(module.PINS), list(module.BUNDLE), tuple(ast.literal_eval(match.group(1))))


def kernel_state(status_output: str) -> tuple[str | None, str | None]:
    """(normalised status, failure message) from `kaggle kernels status` output.
    The CLI prints e.g. `alice/x has status "KernelWorkerStatus.RUNNING"` (older: "running")."""
    match = re.search(r'has status "([^"]+)"', status_output)
    failure = re.search(r'Failure message: "(.*)"', status_output)
    status = match.group(1).rsplit(".", 1)[-1].replace("_", "").lower() if match else None
    return status, failure.group(1) if failure else None


def parse_kernel_log(text: str) -> list[str]:
    """Kaggle's session log is a JSON list of {stream_name, time, data}; fall back to plain text."""
    try:
        entries = json.loads(text)
    except ValueError:
        return text.splitlines()
    if not isinstance(entries, list):
        return text.splitlines()
    return "".join(str(e.get("data", "")) for e in entries if isinstance(e, dict)).splitlines()


class KaggleBackend:
    kind = BackendKind.KAGGLE

    def __init__(
        self,
        ctx: TargetContext,
        *,
        runner: ProcessRunner | None = None,
        clock: Callable[[], float] = time.time,
    ) -> None:
        self.ctx = ctx
        self.config = KaggleConfig.model_validate(ctx.config)
        self.runner = runner or SubprocessRunner()
        self.clock = clock
        self.cli = [sys.executable, "-m", "kaggle"]

    async def validate(self) -> HealthReport:
        if not self.ctx.secret:
            return HealthReport(HealthStatus.DOWN, "Kaggle API key not set")
        listing = await self._cli("kernels", "list", "--mine", "--page-size", "1", timeout_s=60)
        if not listing.ok or "Authentication required" in listing.text:
            return HealthReport(HealthStatus.DOWN, f"Kaggle API check failed: {listing.error_text}")
        quota = _parse_quota(await self._cli("quota", "--csv", timeout_s=60))
        if quota is None:
            return HealthReport(HealthStatus.OK, f"Kaggle API reachable as {self.config.username}")
        if quota["gpu_remaining_hours"] < 1:
            return HealthReport(
                HealthStatus.DEGRADED,
                f"Kaggle weekly GPU quota is nearly used up: {quota['gpu_remaining_hours']:.1f} of "
                f"{quota['gpu_total_hours']:.0f} GPU hours left",
                quota,
            )
        return HealthReport(
            HealthStatus.OK,
            f"Kaggle API reachable; {quota['gpu_remaining_hours']:.1f} of {quota['gpu_total_hours']:.0f} "
            "GPU hours left this week",
            quota,
        )

    async def submit(self, spec: JobSpec) -> ExternalRef:
        if spec.kind != "train":
            raise BackendError("Kaggle targets run train stages only; evaluation runs on local_cpu")
        slug = self._slug(spec)
        kernel = f"{self.config.username}/{slug}"
        existing = await self._cli("kernels", "status", kernel, timeout_s=60)
        if kernel_state(existing.text)[0] is not None:  # already pushed (worker restarted mid-submit)
            return self._ref(kernel, pushed_at=self.clock())
        if not self._not_found(existing):  # pushing again would restart a running kernel
            raise BackendError(f"Kaggle status check failed: {existing.error_text}", retryable=True)
        sources = self._kernel_sources(spec)
        metadata = {
            "id": kernel,
            "title": slug,
            "code_file": "kernel.py",
            "language": "python",
            "kernel_type": "script",
            "is_private": True,
            "enable_gpu": True,
            "enable_internet": self.config.enable_internet,
            "dataset_sources": [],
            "competition_sources": [],
            "kernel_sources": sorted(set(sources.values())),
        }
        with tempfile.TemporaryDirectory(prefix="skf-kernel-") as folder:
            source = await asyncio.to_thread(self._kernel_source, spec, sources)
            await asyncio.to_thread(_write_kernel_folder, Path(folder), source, metadata)
            pushed = await self._cli(
                "kernels",
                "push",
                "-p",
                folder,
                "--accelerator",
                self.config.accelerator,
                "--timeout",
                str(spec.timeout_minutes * 60),
                timeout_s=300,
            )
        output = pushed.text + pushed.stderr.decode(errors="replace")
        if not pushed.ok or "push error" in output.lower() or "successfully pushed" not in output:
            raise BackendError(f"Kaggle push failed: {pushed.error_text or output.strip()[-600:]}")
        return self._ref(kernel, pushed_at=self.clock())

    async def status(self, ref: ExternalRef) -> JobStatus:
        result = await self._cli("kernels", "status", ref.job_id, timeout_s=60)
        status, failure = kernel_state(result.text)
        now = self.clock()
        data = dict(ref.data)
        if status is None:
            if self._not_found(result) and now - float(data.get("pushed_at", now)) < NOT_FOUND_GRACE_SECONDS:
                return JobStatus(JobState.PROVISIONING, "waiting for Kaggle to list the kernel")
            if self._not_found(result):
                return JobStatus(JobState.FAILED, "kernel not found on Kaggle")
            raise BackendError(f"Kaggle status check failed: {result.error_text}", retryable=True)
        state = _STATES.get(status, JobState.PROVISIONING)
        if state is JobState.RUNNING:
            data.setdefault("running_since", now)
        if state.terminal:
            data.setdefault("ended_at", now)
        new_ref = ExternalRef(ref.backend, ref.job_id, data, ref.url)
        return JobStatus(state, failure or status, gpu_seconds=_gpu_seconds(data, now), ref=new_ref)

    async def fetch_logs(self, ref: ExternalRef, cursor: str | None) -> LogBatch:
        """Kaggle only publishes a kernel's log once it has finished, so this returns everything once."""
        if cursor == "done":
            return LogBatch([], cursor)
        state = (await self.status(ref)).state
        if not state.terminal:
            return LogBatch([], cursor)
        with tempfile.TemporaryDirectory(prefix="skf-kaggle-log-") as tmp:
            await self._download(ref, Path(tmp), file_pattern=rf"^{re.escape(JOB_LOG)}$")
            return LogBatch(await asyncio.to_thread(_log_lines, Path(tmp), ref), "done")

    async def collect(self, ref: ExternalRef, dest: Path) -> None:
        staging = self.ctx.work_dir / "kaggle" / ref.job_id.split("/")[-1]
        await asyncio.to_thread(shutil.rmtree, staging, ignore_errors=True)
        await self._download(ref, staging)
        await asyncio.to_thread(_unpack_output, staging, dest, ref)
        await asyncio.to_thread(shutil.rmtree, staging, ignore_errors=True)

    async def cancel(self, ref: ExternalRef) -> None:
        # The public Kaggle API has no call to stop a running session. The kernel stops itself: its
        # reporter runs with --stop-when-revoked and ends the job once the studio rejects its heartbeats
        # (the stage is cancelled), and every kernel is pushed with the stage timeout as a hard limit.
        return None

    async def release(self) -> None:
        return None

    def _slug(self, spec: JobSpec) -> str:
        name = f"{self.config.kernel_prefix}-{spec.run_name}-{spec.stage_key}".lower()
        base = re.sub(r"[^a-z0-9]+", "-", name)
        suffix = re.sub(r"[^a-z0-9]", "", spec.stage_id.lower())[:8]
        return f"{base.strip('-')[:41].rstrip('-')}-{suffix}"  # Kaggle titles/slugs: at most 50 chars

    def _ref(self, kernel: str, *, pushed_at: float) -> ExternalRef:
        return ExternalRef(BackendKind.KAGGLE, kernel, {"pushed_at": pushed_at}, f"{KAGGLE_URL}/{kernel}")

    def _kernel_sources(self, spec: JobSpec) -> dict[str, str]:
        """Input name -> Kaggle kernel whose output holds it."""
        sources: dict[str, str] = {}
        for item in spec.inputs:
            if item.source_ref is None or item.source_ref.backend is not BackendKind.KAGGLE:
                raise BackendError("warm start on Kaggle needs a parent trained on Kaggle")
            sources[item.name] = item.source_ref.job_id
        return sources

    def _kernel_source(self, spec: JobSpec, sources: dict[str, str]) -> str:
        repo = self.ctx.pipeline_repo_dir
        bundle = load_pipeline_bundle(repo / "scripts" / "kaggle_job.py")
        files = {f"g1pipe/{name}": (repo / "g1pipe" / name).read_text() for name in bundle.bundle}
        files["skf_reporter.py"] = (repo / REPORTER_RELPATH).read_text()
        reporter = reporter_args(
            log=f"{WORKING}/{JOB_LOG}",
            exit_file=f"{WORKING}/exit_code",
            progress=f"{OUT_DIR}/{spec.progress_csv}" if spec.progress_csv else None,
            timeout_minutes=spec.timeout_minutes,
        )
        for noise in bundle.noise:
            reporter += ["--noise", noise]
        if spec.ingest is not None:
            reporter.append("--stop-when-revoked")
        # The ingest token is embedded in the (private) kernel: it only grants writing this stage's
        # logs and metrics, and expires shortly after the stage timeout.
        env = {**spec.env, **ingest_env(spec.ingest, spec.stage_id)}
        return KERNEL_TEMPLATE.format(
            run_name=spec.run_name,
            stage_key=spec.stage_key,
            stage_id=spec.stage_id,
            pins=bundle.pins,
            files=files,
            inputs=sources,
            input_dir=INPUT_DIR,
            env=env,
            reporter=reporter,
            argv=render_argv(spec, [], OUT_DIR, INPUT_DIR),
        )

    async def _download(self, ref: ExternalRef, dest: Path, *, file_pattern: str | None = None) -> None:
        args = ["kernels", "output", ref.job_id, "-p", str(dest), "-o", "-q"]
        if file_pattern:
            args += ["--file-pattern", file_pattern]
        result = await self._cli(*args, timeout_s=3600)
        if not result.ok:
            raise BackendError(f"downloading Kaggle output failed: {result.error_text}", retryable=True)

    async def _cli(self, *args: str, timeout_s: float) -> ProcResult:
        if not self.ctx.secret:
            raise BackendError("Kaggle API key not set for this target")
        secret = KaggleSecret.model_validate(self.ctx.secret)
        # A throwaway config dir: the CLI would otherwise create ~/.kaggle for the worker user.
        # Credentials travel in the environment only, never in a file.
        with tempfile.TemporaryDirectory(prefix="skf-kaggle-") as config_dir:
            env = {k: v for k, v in os.environ.items() if k in _ENV_PASSTHROUGH}
            env.update(
                KAGGLE_CONFIG_DIR=config_dir, KAGGLE_USERNAME=self.config.username, KAGGLE_KEY=secret.key
            )
            return await self.runner([*self.cli, *args], env=env, timeout_s=timeout_s)

    @staticmethod
    def _not_found(result: ProcResult) -> bool:
        output = (result.text + result.stderr.decode(errors="replace")).lower()
        return "404" in output or "not found" in output


def _write_kernel_folder(folder: Path, source: str, metadata: dict[str, object]) -> None:
    (folder / "kernel.py").write_text(source)
    (folder / "kernel-metadata.json").write_text(json.dumps(metadata, indent=2))


def _unpack_output(staging: Path, dest: Path, ref: ExternalRef) -> None:
    """Kernel output -> stage outputs: run/* are the job's files; the log becomes job.log."""
    copy_tree(staging / "run", dest)
    lines = _log_lines(staging, ref)
    if lines:
        (dest / JOB_LOG).write_text("\n".join(lines) + "\n")


def _gpu_seconds(data: dict, now: float) -> float | None:
    # A kernel first seen already finished was never observed running: count from the push.
    start = data.get("running_since", data.get("pushed_at") if "ended_at" in data else None)
    if start is None:
        return None
    return max(0.0, float(data.get("ended_at", now)) - float(start))


def _log_lines(folder: Path, ref: ExternalRef) -> list[str]:
    """The reporter's filtered job.log if the kernel got that far, else Kaggle's own session log."""
    job_log = folder / JOB_LOG
    if job_log.is_file():
        return _tail(job_log).splitlines()
    session_log = folder / f"{ref.job_id.split('/')[-1]}.log"
    return parse_kernel_log(_tail(session_log)) if session_log.is_file() else []


def _tail(path: Path) -> str:
    with open(path, "rb") as f:
        f.seek(max(0, path.stat().st_size - LOG_LIMIT_BYTES))
        return f.read().decode("utf-8", errors="replace")


def _parse_quota(result: ProcResult) -> dict[str, float] | None:
    """`kaggle quota --csv` -> GPU hours used/remaining/total; None if unavailable."""
    if not result.ok:
        return None
    for row in csv.DictReader(result.text.splitlines()):
        if row.get("resource") == "GPU":
            try:
                return {f"gpu_{k}_hours": float(row[k].rstrip("h")) for k in ("used", "remaining", "total")}
            except (KeyError, ValueError):
                return None
    return None
