/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Me Get */
    get: operations["me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Skills List */
    get: operations["skills_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/skills/sync": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Skills Sync */
    post: operations["skills_sync"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/skills/{skill_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Skills Get */
    get: operations["skills_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compute-targets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compute Targets List */
    get: operations["compute_targets_list"];
    put?: never;
    /** Compute Targets Create */
    post: operations["compute_targets_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compute-targets/schema/{kind}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compute Targets Schema */
    get: operations["compute_targets_schema"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compute-targets/{target_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Compute Targets Update */
    patch: operations["compute_targets_update"];
    trace?: never;
  };
  "/api/v1/compute-targets/{target_id}/secret": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Compute Targets Set Secret */
    put: operations["compute_targets_set_secret"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compute-targets/{target_id}/check": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Compute Targets Check */
    post: operations["compute_targets_check"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/estimate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs Estimate */
    post: operations["runs_estimate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs List */
    get: operations["runs_list"];
    put?: never;
    /** Runs Create */
    post: operations["runs_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Get */
    get: operations["runs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs Cancel */
    post: operations["runs_cancel"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/retry": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs Retry */
    post: operations["runs_retry"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/launch-decision": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs Launch Decision */
    post: operations["runs_launch_decision"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/review": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs Review */
    post: operations["runs_review"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/evaluate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Runs Evaluate */
    post: operations["runs_evaluate"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Logs */
    get: operations["runs_logs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/logs.txt": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Logs Text */
    get: operations["runs_logs_text"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Metrics */
    get: operations["runs_metrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Artifacts */
    get: operations["runs_artifacts"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/evaluations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Evaluations */
    get: operations["runs_evaluations"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Runs Events */
    get: operations["runs_events"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts/{artifact_id}/url": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Artifacts Url */
    get: operations["artifacts_url"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/approvals": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Approvals List */
    get: operations["approvals_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Compare Runs */
    get: operations["compare_runs"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/dashboard": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dashboard Get */
    get: operations["dashboard_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit List */
    get: operations["audit_list"];
    put?: never;
    /** Audit Create */
    post: operations["audit_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ingest/v1/stages/{stage_id}/logs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest Logs */
    post: operations["ingest_logs"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ingest/v1/stages/{stage_id}/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest Metrics */
    post: operations["ingest_metrics"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ingest/v1/stages/{stage_id}/heartbeat": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ingest Heartbeat */
    post: operations["ingest_heartbeat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Live */
    get: operations["health_live"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/readyz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health Ready */
    get: operations["health_ready"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Approvals */
    Approvals: {
      /** Launches */
      launches: components["schemas"]["RunSummary"][];
      /** Releases */
      releases: components["schemas"]["RunSummary"][];
    };
    /** Artifact */
    Artifact: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Stage Id */
      stage_id: string | null;
      /** Stage Key */
      stage_key: string | null;
      kind: components["schemas"]["ArtifactKind"];
      /** Name */
      name: string;
      /** Size Bytes */
      size_bytes: number;
      /** Content Type */
      content_type: string;
      /** Step */
      step: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /**
     * ArtifactKind
     * @enum {string}
     */
    ArtifactKind: "params" | "checkpoint" | "video" | "image" | "csv" | "json" | "log" | "config" | "other";
    /** ArtifactUrl */
    ArtifactUrl: {
      /** Url */
      url: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /** AuditActor */
    AuditActor: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
    };
    /** AuditEvent */
    AuditEvent: {
      /** Id */
      id: number;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      actor: components["schemas"]["AuditActor"];
      /** Action */
      action: string;
      /** Entity Type */
      entity_type: string;
      /** Entity Id */
      entity_id: string | null;
      /** Detail */
      detail: {
        [key: string]: unknown;
      };
    };
    /** AuditEventCreate */
    AuditEventCreate: {
      /** Action */
      action: string;
      /** Entity Type */
      entity_type: string;
      /** Entity Id */
      entity_id?: string | null;
      /** Detail */
      detail?: {
        [key: string]: unknown;
      };
    };
    /** AuditEventPage */
    AuditEventPage: {
      /** Items */
      items: components["schemas"]["AuditEvent"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /**
     * BackendKind
     * @enum {string}
     */
    BackendKind: "local_cpu" | "kaggle" | "aws_ec2";
    /** BackendSchema */
    BackendSchema: {
      /** Config */
      config: {
        [key: string]: unknown;
      };
      /** Secret */
      secret: {
        [key: string]: unknown;
      };
    };
    /** Comparison */
    Comparison: {
      /** Runs */
      runs: components["schemas"]["RunDetail"][];
      /** Headline Rows */
      headline_rows: components["schemas"]["HeadlineRow"][];
      /** Gate Rows */
      gate_rows: components["schemas"]["GateRow"][];
      /** Metric Keys */
      metric_keys: string[];
    };
    /** ComputeTarget */
    ComputeTarget: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      kind: components["schemas"]["BackendKind"];
      /** Description */
      description: string | null;
      /** Enabled */
      enabled: boolean;
      /** Config */
      config: {
        [key: string]: unknown;
      };
      /** Has Secret */
      has_secret: boolean;
      /** Gpu Label */
      gpu_label: string | null;
      /** Steps Per Second */
      steps_per_second: number;
      /** Overhead Minutes */
      overhead_minutes: number;
      /** Cost Per Gpu Hour */
      cost_per_gpu_hour: number;
      /** Weekly Quota Gpu Hours */
      weekly_quota_gpu_hours: number | null;
      /** Max Unapproved Gpu Hours */
      max_unapproved_gpu_hours: number;
      /** Max Concurrent */
      max_concurrent: number;
      health: components["schemas"]["TargetHealth"];
      usage: components["schemas"]["TargetUsage"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ComputeTargetCreate */
    ComputeTargetCreate: {
      /** Description */
      description?: string | null;
      /**
       * Enabled
       * @default false
       */
      enabled: boolean;
      /** Config */
      config?: {
        [key: string]: unknown;
      };
      /** Gpu Label */
      gpu_label?: string | null;
      /** Steps Per Second */
      steps_per_second: number;
      /**
       * Overhead Minutes
       * @default 0
       */
      overhead_minutes: number;
      /**
       * Cost Per Gpu Hour
       * @default 0
       */
      cost_per_gpu_hour: number;
      /** Weekly Quota Gpu Hours */
      weekly_quota_gpu_hours?: number | null;
      /**
       * Max Unapproved Gpu Hours
       * @default 0
       */
      max_unapproved_gpu_hours: number;
      /**
       * Max Concurrent
       * @default 1
       */
      max_concurrent: number;
      /** Name */
      name: string;
      kind: components["schemas"]["BackendKind"];
    };
    /**
     * ComputeTargetUpdate
     * @description Partial update: only fields present in the request body change.
     */
    ComputeTargetUpdate: {
      /** Name */
      name?: string | null;
      /** Description */
      description?: string | null;
      /** Enabled */
      enabled?: boolean | null;
      /** Config */
      config?: {
        [key: string]: unknown;
      } | null;
      /** Gpu Label */
      gpu_label?: string | null;
      /** Steps Per Second */
      steps_per_second?: number | null;
      /** Overhead Minutes */
      overhead_minutes?: number | null;
      /** Cost Per Gpu Hour */
      cost_per_gpu_hour?: number | null;
      /** Weekly Quota Gpu Hours */
      weekly_quota_gpu_hours?: number | null;
      /** Max Unapproved Gpu Hours */
      max_unapproved_gpu_hours?: number | null;
      /** Max Concurrent */
      max_concurrent?: number | null;
    };
    /** CurrentStage */
    CurrentStage: {
      /** Key */
      key: string;
      /** Title */
      title: string;
      status: components["schemas"]["StageStatus"];
      /** Progress */
      progress: number | null;
    };
    /** Dashboard */
    Dashboard: {
      /** Active Runs */
      active_runs: number;
      /** Awaiting Launch Approval */
      awaiting_launch_approval: number;
      /** Awaiting Review */
      awaiting_review: number;
      /** Gpu Hours 7D */
      gpu_hours_7d: number;
      /** Cost 7D */
      cost_7d: number;
      /** Gate Pass Rate 30D */
      gate_pass_rate_30d: number | null;
      /** Targets */
      targets: components["schemas"]["DashboardTarget"][];
      /** Recent Runs */
      recent_runs: components["schemas"]["RunSummary"][];
      /** Skills */
      skills: components["schemas"]["DashboardSkill"][];
    };
    /** DashboardSkill */
    DashboardSkill: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Runs */
      runs: number;
      /** Gpu Hours Total */
      gpu_hours_total: number;
      best_run: components["schemas"]["RunRef"] | null;
      latest_verdict: components["schemas"]["GateVerdict"] | null;
    };
    /** DashboardTarget */
    DashboardTarget: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      kind: components["schemas"]["BackendKind"];
      /** Gpu Label */
      gpu_label: string | null;
      /** Active Stages */
      active_stages: number;
      /** Quota Left Hours */
      quota_left_hours: number | null;
      health: components["schemas"]["TargetHealth"];
    };
    /** Decision */
    Decision: {
      /**
       * Decision
       * @enum {string}
       */
      decision: "approve" | "reject";
      /** Comment */
      comment?: string | null;
    };
    /** ErrorBody */
    ErrorBody: {
      /** Code */
      code: string;
      /** Message */
      message: string;
      /** Details */
      details?: {
        [key: string]: unknown;
      };
    };
    /** ErrorResponse */
    ErrorResponse: {
      error: components["schemas"]["ErrorBody"];
    };
    /** Estimate */
    Estimate: {
      /** Train Minutes */
      train_minutes: number;
      /** Total Minutes */
      total_minutes: number;
      /** Gpu Hours */
      gpu_hours: number;
      /** Cost */
      cost: number;
      /** Needs Approval */
      needs_approval: boolean;
      /** Reasons */
      reasons: string[];
      /** Warnings */
      warnings: string[];
      /** Blockers */
      blockers: string[];
    };
    /** EstimateRequest */
    EstimateRequest: {
      /** Skill Id */
      skill_id: string;
      /** Preset Id */
      preset_id?: string | null;
      /** Params */
      params?: {
        [key: string]: unknown;
      };
      /**
       * Compute Target Id
       * Format: uuid
       */
      compute_target_id: string;
    };
    /** EvaluateCheckpoint */
    EvaluateCheckpoint: {
      /**
       * Checkpoint Id
       * Format: uuid
       */
      checkpoint_id: string;
      /** Stage Key */
      stage_key?: string | null;
    };
    /** Evaluation */
    Evaluation: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Stage Id
       * Format: uuid
       */
      stage_id: string;
      /** Stage Key */
      stage_key: string;
      checkpoint: components["schemas"]["Artifact"] | null;
      /** Suite */
      suite: string;
      /** Summary */
      summary: {
        [key: string]: unknown;
      };
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** GateCriterion */
    GateCriterion: {
      /** Metric */
      metric: string;
      op: components["schemas"]["GateOp"];
      /** Value */
      value: number;
      /** Label */
      label: string;
      level: components["schemas"]["GateLevel"];
    };
    /** GateCriterionResult */
    GateCriterionResult: {
      /** Metric */
      metric: string;
      /** Label */
      label: string;
      op: components["schemas"]["GateOp"];
      /** Value */
      value: number;
      /** Actual */
      actual: number | null;
      /** Passed */
      passed: boolean;
      /** @default release */
      level: components["schemas"]["GateLevel"];
    };
    /** GateDecision */
    GateDecision: {
      verdict: components["schemas"]["GateVerdict"];
      /** Criteria */
      criteria: components["schemas"]["GateCriterionResult"][];
      /** Levels */
      levels: components["schemas"]["GateLevelResult"][];
      /**
       * Evaluated At
       * Format: date-time
       */
      evaluated_at: string;
      review_status: components["schemas"]["ReviewStatus"];
      reviewer: components["schemas"]["UserRef"] | null;
      /** Comment */
      comment: string | null;
      /** Reviewed At */
      reviewed_at: string | null;
    };
    /** @enum {string} */
    GateLevel: "simulation" | "release";
    /** GateLevelResult */
    GateLevelResult: {
      level: components["schemas"]["GateLevel"];
      verdict: components["schemas"]["GateVerdict"];
      /** Passed */
      passed: number;
      /** Total */
      total: number;
    };
    /** @enum {string} */
    GateOp: "<" | "<=" | ">" | ">=" | "==" | "!=";
    /** GateRow */
    GateRow: {
      /** Label */
      label: string;
      level: components["schemas"]["GateLevel"];
      /** Values */
      values: (boolean | null)[];
    };
    /**
     * GateVerdict
     * @enum {string}
     */
    GateVerdict: "pass" | "fail";
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Headline */
    Headline: {
      /** Label */
      label: string;
      /** Metric */
      metric: string;
      /** Unit */
      unit: string | null;
      /** Scale */
      scale: number | null;
      /** Digits */
      digits: number | null;
    };
    /** HeadlineRow */
    HeadlineRow: {
      /** Label */
      label: string;
      /** Unit */
      unit: string | null;
      /** Values */
      values: (number | null)[];
    };
    /** HeadlineValue */
    HeadlineValue: {
      /** Label */
      label: string;
      /** Value */
      value: number | null;
      /** Unit */
      unit: string | null;
    };
    /** Health */
    Health: {
      /** Status */
      status: string;
      /** Checks */
      checks: {
        [key: string]: string;
      };
    };
    /** Heartbeat */
    Heartbeat: {
      /** Progress */
      progress?: number | null;
      /** Message */
      message?: string | null;
    };
    /** IncomingLine */
    IncomingLine: {
      /** Ts */
      ts?: string | null;
      /** Text */
      text: string;
      /** Stream */
      stream?: ("stdout" | "stderr") | null;
    };
    /** IngestAck */
    IngestAck: {
      /** Accepted */
      accepted: number;
      /**
       * Dropped
       * @default 0
       */
      dropped: number;
    };
    /** LogBatch */
    LogBatch: {
      /** Lines */
      lines: components["schemas"]["IncomingLine"][];
      /**
       * Noise Dropped
       * @default 0
       */
      noise_dropped: number;
    };
    /**
     * LogLevel
     * @enum {string}
     */
    LogLevel: "info" | "warn" | "error";
    /** LogLine */
    LogLine: {
      /** Id */
      id: number;
      /**
       * Stage Id
       * Format: uuid
       */
      stage_id: string;
      /**
       * Ts
       * Format: date-time
       */
      ts: string;
      level: components["schemas"]["LogLevel"];
      /** Text */
      text: string;
    };
    /** LogPage */
    LogPage: {
      /** Items */
      items: components["schemas"]["LogLine"][];
      /** Next After Id */
      next_after_id: number | null;
    };
    /** Me */
    Me: {
      /** Id */
      id: string;
      /** Email */
      email: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Permissions */
      permissions: string[];
    };
    /** MetricBatch */
    MetricBatch: {
      /** Points */
      points: components["schemas"]["MetricPointIn"][];
    };
    /** MetricPointIn */
    MetricPointIn: {
      /** Step */
      step: number;
      /** Wall S */
      wall_s?: number | null;
      /** Values */
      values: {
        [key: string]: number;
      };
    };
    /** MetricSeries */
    MetricSeries: {
      /** Key */
      key: string;
      /** Points */
      points: [number, number][];
    };
    /** Metrics */
    Metrics: {
      /** Keys */
      keys: string[];
      /** Series */
      series: components["schemas"]["MetricSeries"][];
    };
    /** PipelineStageDef */
    PipelineStageDef: {
      /** Id */
      id: string;
      kind: components["schemas"]["StageKind"];
      /** Title */
      title: string;
      runs_on: components["schemas"]["RunsOn"];
    };
    /** Preset */
    Preset: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Params */
      params: {
        [key: string]: unknown;
      };
    };
    /** @enum {string} */
    QuotaSource: "ledger" | "provider";
    /**
     * ReviewStatus
     * @enum {string}
     */
    ReviewStatus: "pending" | "approved" | "rejected" | "not_required";
    /** RunCreate */
    RunCreate: {
      /** Skill Id */
      skill_id: string;
      /** Preset Id */
      preset_id?: string | null;
      /** Params */
      params?: {
        [key: string]: unknown;
      };
      /**
       * Compute Target Id
       * Format: uuid
       */
      compute_target_id: string;
      /** Name */
      name?: string | null;
      /** Notes */
      notes?: string | null;
      /** Parent Run Id */
      parent_run_id?: string | null;
      /** Parent Checkpoint Id */
      parent_checkpoint_id?: string | null;
    };
    /** RunDetail */
    RunDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Skill Id */
      skill_id: string;
      /** Skill Name */
      skill_name: string;
      /** Preset Id */
      preset_id: string | null;
      status: components["schemas"]["RunStatus"];
      compute_target: components["schemas"]["TargetRef"] | null;
      created_by: components["schemas"]["UserRef"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Started At */
      started_at: string | null;
      /** Finished At */
      finished_at: string | null;
      current_stage: components["schemas"]["CurrentStage"] | null;
      gate_verdict: components["schemas"]["GateVerdict"] | null;
      simulation_verdict: components["schemas"]["GateVerdict"] | null;
      parent: components["schemas"]["RunParent"] | null;
      /** Imported */
      imported: boolean;
      /** Gpu Hours */
      gpu_hours: number;
      /** Cost */
      cost: number;
      /** Headline */
      headline: components["schemas"]["HeadlineValue"][];
      /** Params */
      params: {
        [key: string]: unknown;
      };
      /** Git Sha */
      git_sha: string | null;
      /** Notes */
      notes: string | null;
      /** Error */
      error: string | null;
      estimate: components["schemas"]["Estimate"] | null;
      /** Children */
      children: components["schemas"]["RunRef"][];
      /** Stages */
      stages: components["schemas"]["Stage"][];
      gate: components["schemas"]["GateDecision"] | null;
      launch_decided_by: components["schemas"]["UserRef"] | null;
      /** Launch Decided At */
      launch_decided_at: string | null;
      permissions: components["schemas"]["RunPermissions"];
    };
    /** RunPage */
    RunPage: {
      /** Items */
      items: components["schemas"]["RunSummary"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /** RunParent */
    RunParent: {
      run: components["schemas"]["RunRef"];
      checkpoint: components["schemas"]["Artifact"] | null;
    };
    /** RunPermissions */
    RunPermissions: {
      /** Can Cancel */
      can_cancel: boolean;
      /** Can Retry */
      can_retry: boolean;
      /** Can Approve Launch */
      can_approve_launch: boolean;
      /** Can Review */
      can_review: boolean;
      /** Can Evaluate */
      can_evaluate: boolean;
    };
    /** RunRef */
    RunRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      status: components["schemas"]["RunStatus"];
    };
    /**
     * RunStatus
     * @enum {string}
     */
    RunStatus:
      | "pending_approval"
      | "queued"
      | "running"
      | "awaiting_review"
      | "approved"
      | "rejected"
      | "gate_failed"
      | "failed"
      | "cancelled";
    /** RunSummary */
    RunSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Skill Id */
      skill_id: string;
      /** Skill Name */
      skill_name: string;
      /** Preset Id */
      preset_id: string | null;
      status: components["schemas"]["RunStatus"];
      compute_target: components["schemas"]["TargetRef"] | null;
      created_by: components["schemas"]["UserRef"];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Started At */
      started_at: string | null;
      /** Finished At */
      finished_at: string | null;
      current_stage: components["schemas"]["CurrentStage"] | null;
      gate_verdict: components["schemas"]["GateVerdict"] | null;
      simulation_verdict: components["schemas"]["GateVerdict"] | null;
      parent: components["schemas"]["RunParent"] | null;
      /** Imported */
      imported: boolean;
      /** Gpu Hours */
      gpu_hours: number;
      /** Cost */
      cost: number;
      /** Headline */
      headline: components["schemas"]["HeadlineValue"][];
    };
    /**
     * RunsOn
     * @enum {string}
     */
    RunsOn: "target" | "local";
    /**
     * SkillCategory
     * @enum {string}
     */
    SkillCategory: "locomotion" | "manipulation" | "workflow";
    /** SkillDetail */
    SkillDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Summary */
      summary: string;
      /** Robot */
      robot: string;
      category: components["schemas"]["SkillCategory"];
      /** Method */
      method: string;
      status: components["schemas"]["SkillStatus"];
      /** Git Sha */
      git_sha: string | null;
      /** Run Count */
      run_count: number;
      /** Last Run At */
      last_run_at: string | null;
      best_run: components["schemas"]["RunRef"] | null;
      /** Description */
      description: string;
      /** Params Schema */
      params_schema: {
        [key: string]: unknown;
      };
      /** Presets */
      presets: components["schemas"]["Preset"][];
      /** Pipeline */
      pipeline: components["schemas"]["PipelineStageDef"][];
      /** Gate */
      gate: components["schemas"]["GateCriterion"][];
      /** Headline */
      headline: components["schemas"]["Headline"][];
      metrics: components["schemas"]["SkillMetrics"];
    };
    /** SkillMetrics */
    SkillMetrics: {
      /** Keys */
      keys: string[];
      /** Primary */
      primary: string | null;
    };
    /** SkillPage */
    SkillPage: {
      /** Items */
      items: components["schemas"]["SkillSummary"][];
      /** Next Cursor */
      next_cursor: string | null;
    };
    /**
     * SkillStatus
     * @enum {string}
     */
    SkillStatus: "draft" | "active" | "deprecated";
    /** SkillSummary */
    SkillSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Summary */
      summary: string;
      /** Robot */
      robot: string;
      category: components["schemas"]["SkillCategory"];
      /** Method */
      method: string;
      status: components["schemas"]["SkillStatus"];
      /** Git Sha */
      git_sha: string | null;
      /** Run Count */
      run_count: number;
      /** Last Run At */
      last_run_at: string | null;
      best_run: components["schemas"]["RunRef"] | null;
    };
    /** Stage */
    Stage: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Key */
      key: string;
      kind: components["schemas"]["StageKind"];
      /** Title */
      title: string;
      /** Position */
      position: number;
      runs_on: components["schemas"]["RunsOn"];
      status: components["schemas"]["StageStatus"];
      /** Compute Target Id */
      compute_target_id: string | null;
      /** Attempt */
      attempt: number;
      /** Progress */
      progress: number | null;
      /** Message */
      message: string | null;
      /** Started At */
      started_at: string | null;
      /** Finished At */
      finished_at: string | null;
      /** Last Heartbeat At */
      last_heartbeat_at: string | null;
      /** Gpu Seconds */
      gpu_seconds: number;
      /** Cost */
      cost: number;
      /** Noise Dropped */
      noise_dropped: number;
      /** Error */
      error: string | null;
      /** External Url */
      external_url: string | null;
      checkpoint: components["schemas"]["Artifact"] | null;
    };
    /**
     * StageKind
     * @enum {string}
     */
    StageKind: "train" | "evaluate" | "gate";
    /**
     * StageStatus
     * @enum {string}
     */
    StageStatus:
      | "pending"
      | "queued"
      | "provisioning"
      | "running"
      | "collecting"
      | "succeeded"
      | "failed"
      | "cancelled"
      | "skipped";
    /** SyncError */
    SyncError: {
      /** File */
      file: string;
      /** Message */
      message: string;
    };
    /** SyncResult */
    SyncResult: {
      /** Synced */
      synced: string[];
      /** Errors */
      errors: components["schemas"]["SyncError"][];
    };
    /** TargetHealth */
    TargetHealth: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded" | "down" | "unknown";
      /** Message */
      message: string;
      /** Checked At */
      checked_at: string | null;
    };
    /** TargetRef */
    TargetRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      kind: components["schemas"]["BackendKind"];
    };
    /** TargetSecret */
    TargetSecret: {
      /** Secret */
      secret: {
        [key: string]: unknown;
      };
    };
    /** TargetUsage */
    TargetUsage: {
      /** Gpu Hours 7D */
      gpu_hours_7d: number;
      /** Cost 7D */
      cost_7d: number;
      /** Active Stages */
      active_stages: number;
      /** Quota Left Hours */
      quota_left_hours: number | null;
      quota_source: components["schemas"]["QuotaSource"] | null;
    };
    /** UserRef */
    UserRef: {
      /** Id */
      id: string;
      /** Name */
      name: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  skills_list: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillPage"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  skills_sync: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SyncResult"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  skills_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        skill_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SkillDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compute_targets_list: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComputeTarget"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compute_targets_create: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComputeTargetCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComputeTarget"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compute_targets_schema: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        kind: components["schemas"]["BackendKind"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BackendSchema"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compute_targets_update: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        target_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComputeTargetUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComputeTarget"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compute_targets_set_secret: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        target_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetSecret"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compute_targets_check: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        target_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComputeTarget"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_estimate: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EstimateRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Estimate"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_list: {
    parameters: {
      query?: {
        skill_id?: string | null;
        status?: components["schemas"]["RunStatus"] | null;
        created_by?: "me" | null;
        q?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunPage"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_create: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_cancel: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_retry: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_launch_decision: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Decision"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_review: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Decision"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_evaluate: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EvaluateCheckpoint"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunDetail"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_logs: {
    parameters: {
      query?: {
        stage_id?: string | null;
        after_id?: number;
        limit?: number;
        level?: components["schemas"]["LogLevel"] | null;
        q?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogPage"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_logs_text: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_metrics: {
    parameters: {
      query?: {
        /** @description Comma-separated metric keys */
        keys?: string | null;
        stage_id?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Metrics"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_artifacts: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Artifact"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_evaluations: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Evaluation"][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  runs_events: {
    parameters: {
      query?: {
        after_log_id?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": unknown;
        };
      };
      /** @description Error */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Error */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  artifacts_url: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        artifact_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtifactUrl"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  approvals_list: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Approvals"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  compare_runs: {
    parameters: {
      query: {
        /** @description 2-4 comma-separated run ids */
        run_ids: string;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comparison"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  dashboard_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Dashboard"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  audit_list: {
    parameters: {
      query?: {
        actor_id?: string | null;
        action?: string | null;
        entity_type?: string | null;
        limit?: number;
        cursor?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEventPage"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  audit_create: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuditEventCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEvent"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  ingest_logs: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        stage_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LogBatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestAck"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  ingest_metrics: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        stage_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["MetricBatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestAck"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  ingest_heartbeat: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        stage_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Heartbeat"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IngestAck"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Forbidden */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Conflict */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health_live: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  health_ready: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
}
