/**
 * Types of the Skill Studio API, aliased from the OpenAPI schema (`schema.d.ts`, generated by `pnpm gen:api`).
 * Nothing here restates a response shape: when the API changes, regenerating the schema makes `tsc` point at
 * every place in the web app that no longer matches.
 */
import type { components } from "./schema";

type Schemas = components["schemas"];

export type ISODateTime = string;

// Enumerations
export type Category = Schemas["SkillCategory"];
export type SkillStatus = Schemas["SkillStatus"];
export type ComputeKind = Schemas["BackendKind"];
export type StageKind = Schemas["StageKind"];
export type RunsOn = Schemas["RunsOn"];
export type LogLevel = Schemas["LogLevel"];
export type GateVerdict = Schemas["GateVerdict"];
export type ReviewStatus = Schemas["ReviewStatus"];
export type HealthStatus = Schemas["TargetHealth"]["status"];
export type Decision = Schemas["Decision"]["decision"];
export type ArtifactKind = Schemas["ArtifactKind"];
export type GateOp = Schemas["GateOp"];
export type RunStatus = Schemas["RunStatus"];
export type StageStatus = Schemas["StageStatus"];

// Resources
export type Me = Schemas["Me"];
export type UserRef = Schemas["UserRef"];
export type RunRef = Schemas["RunRef"];
export type SkillSummary = Schemas["SkillSummary"];
export type SkillPage = Schemas["SkillPage"];
export type Preset = Schemas["Preset"];
export type PipelineStageDef = Schemas["PipelineStageDef"];
export type GateCriterion = Schemas["GateCriterion"];
export type Headline = Schemas["Headline"];
export type ComputeHealth = Schemas["TargetHealth"];
export type ComputeUsage = Schemas["TargetUsage"];
export type ComputeTarget = Schemas["ComputeTarget"];
export type Estimate = Schemas["Estimate"];
export type Artifact = Schemas["Artifact"];
export type ArtifactUrl = Schemas["ArtifactUrl"];
export type Stage = Schemas["Stage"];
export type HeadlineValue = Schemas["HeadlineValue"];
export type RunSummary = Schemas["RunSummary"];
export type RunPage = Schemas["RunPage"];
export type GateCriterionResult = Schemas["GateCriterionResult"];
export type GateDecision = Schemas["GateDecision"];
export type RunPermissions = Schemas["RunPermissions"];
export type RunDetail = Schemas["RunDetail"];
export type LogLine = Schemas["LogLine"];
export type LogPage = Schemas["LogPage"];
export type MetricSeries = Schemas["MetricSeries"];
export type MetricsResponse = Schemas["Metrics"];
export type Evaluation = Schemas["Evaluation"];
export type AuditEvent = Schemas["AuditEvent"];
export type AuditEventPage = Schemas["AuditEventPage"];
export type SkillSyncResult = Schemas["SyncResult"];
export type Approvals = Schemas["Approvals"];
export type CompareResponse = Schemas["Comparison"];
export type DashboardTarget = Schemas["DashboardTarget"];
export type DashboardSkill = Schemas["DashboardSkill"];
export type Dashboard = Schemas["Dashboard"];

// Request bodies
export type ComputeTargetInput = Schemas["ComputeTargetCreate"];
export type ComputeTargetUpdate = Schemas["ComputeTargetUpdate"];
export type EstimateRequest = Schemas["EstimateRequest"];
export type CreateRunRequest = Schemas["RunCreate"];
export type DecisionRequest = Schemas["Decision"];
export type AuditEventInput = Schemas["AuditEventCreate"];

/**
 * A JSON Schema document as the API produces it (pydantic's `model_json_schema()` and skill params).
 * The OpenAPI schema can only call these "an object"; this is the part of JSON Schema the forms read.
 */
export interface JsonSchema {
  type?: string | string[];
  title?: string;
  description?: string;
  default?: unknown;
  enum?: unknown[];
  const?: unknown;
  format?: string;
  minimum?: number;
  maximum?: number;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  anyOf?: JsonSchema[];
  allOf?: JsonSchema[];
  $ref?: string;
  $defs?: Record<string, JsonSchema>;
  writeOnly?: boolean;
  minLength?: number;
  additionalProperties?: boolean;
  /** Skill manifests mark warm-start parameters with `"checkpoint"`. */
  "x-kind"?: string;
}

export type SkillDetail = Omit<Schemas["SkillDetail"], "params_schema"> & { params_schema: JsonSchema };
export type ComputeTargetSchema = { config: JsonSchema; secret: JsonSchema } & Omit<
  Schemas["BackendSchema"],
  "config" | "secret"
>;

/** Server-sent events on `GET /runs/{id}/events` (SPEC §9.3); SSE payloads are not part of OpenAPI. */
export type RunEvent =
  | { type: "log"; data: LogLine }
  | { type: "metric"; data: { stage_id: string; step: number; values: Record<string, number> } }
  | { type: "stage"; data: Stage }
  | { type: "run"; data: RunSummary };
