"""Run g1pipe training on a Kaggle GPU from the Mac.

    uv run scripts/kaggle_job.py push   --name steplength-probe --timesteps 5000000
    uv run scripts/kaggle_job.py status --name steplength-probe
    uv run scripts/kaggle_job.py pull   --name steplength-probe      # -> runs/<name>/

Bundles g1pipe/*.py into one private Kaggle script kernel (Kaggle takes a single
file), pins the package versions we tested locally, trains, and leaves
params/checkpoints/progress in /kaggle/working for `pull`.
Uses the Kaggle API key in ~/.kaggle/kaggle.json (never read or printed here).
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JOBS = ROOT / "kaggle_jobs"
BUNDLE = ["__init__.py", "steplength_env.py", "train.py"]
PINS = ["playground==0.2.0", "brax==0.14.2", "jax[cuda12]==0.7.2", "flax==0.12.0",
        "mujoco==3.14.0", "mujoco-mjx==3.14.0", "warp-lang==1.17.0"]

KERNEL = '''# Auto-generated by scripts/kaggle_job.py — edit g1pipe/ instead.
import os, subprocess, sys, pathlib, shutil, time
t0 = time.time()
subprocess.run("nvidia-smi", shell=True)
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *{pins!r}])
FILES = {files!r}
pkg = pathlib.Path("/kaggle/working/src/g1pipe"); pkg.mkdir(parents=True, exist_ok=True)
for name, src in FILES.items():
    (pkg / name).write_text(src)
print(f"install {{time.time()-t0:.0f}}s", flush=True)
env = dict(os.environ, PYTHONPATH="/kaggle/working/src", XLA_PYTHON_CLIENT_MEM_FRACTION="0.9")
p = subprocess.Popen([sys.executable, "-u", "-m", "g1pipe.train", "--out", "/kaggle/working/run", *{args!r}],
                     env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
NOISE = ("iterations limit reached", "To disable the print warning", "Warning", "warnings.warn")
for line in p.stdout:  # MuJoCo Warp prints a solver-overflow note every step; keep the log readable
    if not any(n in line for n in NOISE):
        print(line, end="", flush=True)
rc = p.wait()
shutil.rmtree("/kaggle/working/src", ignore_errors=True)
sys.exit(rc)
'''


def kaggle(*args):
    return subprocess.run(["kaggle", *args], text=True, capture_output=True)


def username():
    return json.loads((Path.home() / ".kaggle" / "kaggle.json").read_text())["username"]


def push(a):
    job = JOBS / a.name
    job.mkdir(parents=True, exist_ok=True)
    files = {n: (ROOT / "g1pipe" / n).read_text() for n in BUNDLE}
    args = ["--timesteps", str(a.timesteps), *a.extra]
    (job / "train_kernel.py").write_text(KERNEL.format(pins=PINS, files=files, args=args))
    (job / "kernel-metadata.json").write_text(json.dumps({
        "id": f"{username()}/{a.name}",
        "title": a.name,
        "code_file": "train_kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "dataset_sources": [], "competition_sources": [], "kernel_sources": [],
    }, indent=2))
    r = kaggle("kernels", "push", "-p", str(job), "--accelerator", a.accelerator)
    print(r.stdout, r.stderr)


def status(a):
    r = kaggle("kernels", "status", f"{username()}/{a.name}")
    print(r.stdout.strip(), r.stderr.strip())


def pull(a):
    out = ROOT / "runs" / a.name
    out.mkdir(parents=True, exist_ok=True)
    r = kaggle("kernels", "output", f"{username()}/{a.name}", "-p", str(out), "-o")
    print(r.stdout[-2000:], r.stderr[-2000:])


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["push", "status", "pull"])
    ap.add_argument("--name", required=True, help="kernel slug, lowercase-with-dashes")
    ap.add_argument("--timesteps", type=int, default=150_000_000)
    ap.add_argument("--accelerator", default="NvidiaTeslaT4")
    ap.add_argument("--extra", default="", help='extra args for g1pipe.train, e.g. --extra="--no-dr"')
    a = ap.parse_args()
    a.extra = a.extra.split()
    {"push": push, "status": status, "pull": pull}[a.cmd](a)
