"""Generate notebooks/train_colab.ipynb — the same training job as kaggle_job.py, for Google Colab.

    uv run python scripts/make_colab.py
Then in Colab: File → Upload notebook → Runtime → Change runtime type → T4 GPU → Run all.
Checkpoints go to Google Drive (survive disconnects); the last cell zips the run for download.
Warm start: put the starting params.pkl on Drive (e.g. MyDrive/g1pipe_init/g1-stairs-v2.pkl) and set INIT_FROM.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from kaggle_job import BUNDLE, PINS, ROOT  # noqa: E402


def cell(src, kind="code"):
    c = {"cell_type": kind, "metadata": {}, "source": src}
    if kind == "code":
        c.update(outputs=[], execution_count=None)
    return c


files = {n: (ROOT / "g1pipe" / n).read_text() for n in BUNDLE}
cells = [
    cell("# G1 step-length training (Colab)\n"
         "Generated by `scripts/make_colab.py`. Edit `g1pipe/` in the repo, not this notebook.\n\n"
         "1. Runtime → Change runtime type → **T4 GPU**\n2. Set `TIMESTEPS` / `RUN_NAME` below\n3. Run all. "
         "Checkpoints are written to Google Drive every eval, so a disconnect loses at most one eval interval.", "markdown"),
    cell("TIMESTEPS = 200_000_000   # 5_000_000 for a quick probe\n"
         "RUN_NAME = 'g1-stairs-v4'\n"
         "EXTRA_ARGS = ['--task', 'stairs', '--scan-model', 'camera']   # [] for flat step length; ['--no-dr'] for E3\n"
         "INIT_FROM = 'g1pipe_init/g1-stairs-v3.pkl'   # params.pkl to warm-start from, relative to MyDrive; '' for none\n"
         "USE_DRIVE = True"),
    cell("!nvidia-smi\n"
         f"!pip install -q {' '.join(repr(p) for p in PINS)}"),
    cell("import pathlib\n"
         f"FILES = {files!r}\n"
         "pkg = pathlib.Path('/content/src/g1pipe'); pkg.mkdir(parents=True, exist_ok=True)\n"
         "for name, src in FILES.items():\n    (pkg / name).write_text(src)\n"
         "print('wrote', list(FILES))"),
    cell("import os\n"
         "if USE_DRIVE:\n"
         "    from google.colab import drive\n"
         "    drive.mount('/content/drive')\n"
         "    OUT = f'/content/drive/MyDrive/g1pipe_runs/{RUN_NAME}'\n"
         "else:\n"
         "    OUT = f'/content/runs/{RUN_NAME}'\n"
         "os.makedirs(OUT, exist_ok=True); print(OUT)"),
    cell("import subprocess, sys, os\n"
         "env = dict(os.environ, PYTHONPATH='/content/src', XLA_PYTHON_CLIENT_MEM_FRACTION='0.9')\n"
         "init = ['--init-from', f'/content/drive/MyDrive/{INIT_FROM}'] if (INIT_FROM and USE_DRIVE) else []\n"
         "cmd = [sys.executable, '-u', '-m', 'g1pipe.train', '--out', OUT, '--timesteps', str(TIMESTEPS), *EXTRA_ARGS, *init]\n"
         "p = subprocess.Popen(cmd, env=env, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n"
         "for line in p.stdout:\n"
         "    if 'Warning' not in line and 'warn(' not in line:\n"
         "        print(line, end='')\n"
         "print('exit code', p.wait())"),
    cell("import pandas as pd, matplotlib.pyplot as plt\n"
         "df = pd.read_csv(f'{OUT}/progress.csv'); display(df.tail())\n"
         "cols = [c for c in df.columns if c in ('eval/episode_reward', 'eval/episode_reward/step_length', 'eval/episode_crossed')]\n"
         "df.plot(x='step', y=cols, subplots=True, figsize=(8, 6)); plt.show()"),
    cell("# Download params + progress (checkpoints stay on Drive)\n"
         "import shutil, tempfile, pathlib\n"
         "tmp = pathlib.Path(tempfile.mkdtemp()) / RUN_NAME / 'run'\n"
         "shutil.copytree(OUT, tmp, ignore=shutil.ignore_patterns('ckpt_*'))\n"
         "zip_path = shutil.make_archive(f'/content/{RUN_NAME}', 'zip', tmp.parent.parent)\n"
         "from google.colab import files as _f; _f.download(zip_path)"),
]
nb = {"cells": cells, "metadata": {"accelerator": "GPU", "colab": {"provenance": [], "gpuType": "T4"},
                                   "kernelspec": {"name": "python3", "display_name": "Python 3"}},
      "nbformat": 4, "nbformat_minor": 0}
out = ROOT / "notebooks" / "train_colab.ipynb"
out.parent.mkdir(exist_ok=True)
out.write_text(json.dumps(nb, indent=1))
print("wrote", out)
