import type { FieldSpec } from "@/lib/form-fields";

/** Fields every compute target has, whatever its backend (SPEC §9.2 create body). */
export const COMMON_TARGET_FIELDS: FieldSpec[] = [
  { name: "name", label: "Name", kind: "string", nullable: false, required: true, defaultValue: "" },
  {
    name: "gpu_label",
    label: "GPU label",
    description: "Shown on cards, e.g. 1x T4.",
    kind: "string",
    nullable: true,
    required: false,
    defaultValue: null,
  },
  { name: "description", label: "Description", kind: "string", nullable: true, required: false, defaultValue: null },
  {
    name: "enabled",
    label: "Enabled",
    description: "Disabled targets can't take new runs.",
    kind: "boolean",
    nullable: false,
    required: true,
    defaultValue: true,
  },
  {
    name: "steps_per_second",
    label: "Throughput (steps/s)",
    description: "Measured training throughput, used for estimates.",
    kind: "number",
    nullable: false,
    required: true,
    defaultValue: 36000,
    min: 1,
  },
  {
    name: "overhead_minutes",
    label: "Overhead (min)",
    description: "Provisioning, JIT and upload time per run.",
    kind: "number",
    nullable: false,
    required: true,
    defaultValue: 10,
    min: 0,
  },
  {
    name: "cost_per_gpu_hour",
    label: "Cost per GPU-hour (USD)",
    kind: "number",
    nullable: false,
    required: true,
    defaultValue: 0,
    min: 0,
  },
  {
    name: "weekly_quota_gpu_hours",
    label: "Weekly quota (GPU-h)",
    description: "Leave empty for no quota.",
    kind: "number",
    nullable: true,
    required: false,
    defaultValue: null,
    min: 0,
  },
  {
    name: "max_unapproved_gpu_hours",
    label: "Approval threshold (GPU-h)",
    description: "Operator runs above this need approval.",
    kind: "number",
    nullable: false,
    required: true,
    defaultValue: 2,
    min: 0,
  },
  {
    name: "max_concurrent",
    label: "Max concurrent stages",
    kind: "integer",
    nullable: false,
    required: true,
    defaultValue: 1,
    min: 1,
  },
];
